### ISSUE TITLE
Sprint 2 reviews

### ISSUE THREAD

**Issue by zee7han** [greyatom-school/the-minerva-project#9]
As I have read the content of the sprint2, it looks good but I have a few points which need to take care of:
- We need to describe a mobile-first approach or adaptive design bit more.
- We need to describe the material-UI design which is very helpful designing the react components.
- We need to discuss the module like a compass which is used to compile the pre-processors file like.

**Comment by shettayyy** [comment]
Thanks for the feedback. @zee7han 

1. What did you find missing in the mobile-first approach?
https://www.uxpin.com/studio/blog/a-hands-on-guide-to-mobile-first-design/ covers the concept in detail. https://zellwk.com/blog/how-to-write-mobile-first-css/ provides guidelines on implementing the mobile-first design. I'd like to know about the missing piece :)

2. I can introduce students to material design but it is not just related to responsive design. It is more of a concept that's quite vast and is not restricted to responsive design or web. 
Material UI seems to be quite extensively used with libraries like React or Angular. It should be rather introduced in those sprints. We have already introduced them to Bootstrap. There is Foundation, Semantic-UI, MUICSS, etc. Covering the bases of all these libraries doesn't seem quite efficient for the course. Picking up other libraries should be fairly easy if they at least understand one library thoroughly.

3. Again my focus is more on introducing students to the basics of the concepts rather than throwing them into a pool of plethora of tools. Vastness of the frontend is well known. Also, visit their official website: http://compass-style.org/install/
It has a dependency on Ruby. Why Ruby if I can do everything with Node? Hence, many are trying to replace it. Legacy projects or firms unaware of better tools use compass and add an unnecessary dependency to their project. There is a node wrapper https://www.npmjs.com/package/compass
Again, look at the downloads. Plus who'd keep updating this wrapper? Doesn't seem like a wide community is using it. There has been a steady decline in compass usage. Moreover, due to the css module offered to popular libraries via bundlers, developers are supposed to refrain from using pre-processors. You can read about this in the official documentation of React.

I am not saying pre-processor is not required. Learning one should give them an idea of how to pick up similar other libraries. Don't we as developers do the same? ;)

I want students to invest more time in understanding the basics than a framework. I hope it helps :)

**Comment by zee7han** [comment]
Thanks for the response @rashtay 
Got your points things are well explained and links provided are also good but I am seeing this in the context of the whole course as it is a ReactJS developer course so the student should know about the framework used with ReactJS and relate with the current industry standards.
It is going to be a full-proof course for a frontend developer then the student should know about the modules/process to generate the CSS from the pre-processors.

**Comment by shettayyy** [comment]
I have included the overview for Material design. But, I strongly recommend that MaterialUI should be included in the unit dedicated to React and not in this unit. This unit is already kinda overwhelming.

Regarding:

> to generate the CSS from the pre-processors

SASS already covers what you are asking for and rest are just similar to it. Be it compass, less or stylus :)
